### PR TITLE
Upd for swift 4.2

### PR DESCRIPTION
**Pull request by rmuhamedgaliev**

### CODE REVIEW

**Comment by kukushi** [comment]
Thanks for your PR while there is already a swift4.2 branch.
And I have release the 1.0.0 version for Swift4.2.

**Comment by rmuhamedgaliev** [comment]
👍 when you release new version?

**Comment by kukushi** [comment]
It’s released about ten minutes ago.

**Comment by rmuhamedgaliev** [comment]
@kukushi thanks!

**Pull request closed without merging**
